// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookstoreApi.Models.EFModels;

public partial class Author
{
    public int AuthorId { get; set; }

    public string AuthorName { get; set; }

    public string Biography { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}